<a href="https://colab.research.google.com/github/rasathuraikaran/Machinelearning/blob/main/Simple_Lineaar_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression


In [5]:
x=np.array([25,35,45,55,65,75])
y=np.array([5,20,14,32,22,38])


In [6]:
x

array([25, 35, 45, 55, 65, 75])

In [7]:
y

array([ 5, 20, 14, 32, 22, 38])

In [8]:
x=x.reshape((-1,1))

In [9]:
x

array([[25],
       [35],
       [45],
       [55],
       [65],
       [75]])

In [10]:
model=LinearRegression()

In [11]:
model.fit(x,y)

LinearRegression()

In [13]:
model.score(x,y)

0.7158756137479542

In [14]:
y_pred=model.predict(x)
y_pred

array([ 8.33333333, 13.73333333, 19.13333333, 24.53333333, 29.93333333,
       35.33333333])